name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows,     os: windows-latest }
        - { name: Linux,   os: ubuntu-latest }
        - { name: macOS,       os: macos-latest  }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev libharfbuzz-dev libmbedtls-dev libssh2-1-dev

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Upload
      if: github.ref_type == 'tag'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.platform.name }}
        path: ${{ case(matrix.platform.name == 'Windows', 'build/bin/Release/Bugs.exe', 'build/bin/Bugs') }}
        retention-days: 1

  release:
    name: Publish Release
    needs: build
    permissions:
      contents: write
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
      - name: Package
        run: for dir in *; do zip -j Bugs_${{ github.ref_name }}_${dir}.zip ${dir}/*; done
      - name: Publish Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.zip